### ISSUE TITLE
The docs link is broken

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_MONSTERM4SK#4]
The Sphinx build runs okay locally, and passes actions. I'm not sure if there is something else that needs to be done in the repo or if it's an external system perhaps.

**Comment by kattni** [comment]
@FoamyGuy Thanks for catching this. It's something that needs to be done externally. I'll add it to my list.

**Comment by kattni** [comment]
This was fixed.
