### ISSUE TITLE
Remove setup.py?

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/Adafruit_CircuitPython_MONSTERM4SK#7]
From the Readme:
```
Installing from PyPI

This library will not be available on PyPI. Install documentation is included as a standard element.
```

The current cookie cutter template generates an empty `setup.py.disabled` instead of a `setup.py` if PyPI uploads are not wanted.

Should the `setup.py` be removed and replaced with a `setup.py.disabled`? Or is `setup.py` needed for something else?

__Note:__ I don't have a Monster M4sk to test this against

**Comment by FoamyGuy** [comment]
Yep you're correct. It should be changed to `setup.py.disabled` for this library. Since it's only used for a specific piece of hardware that can't use pypi there is no need to have it deployed there.
